language: node_js
node_js:
  - 16

services:
  - docker

# Scripts to be run such as test
before_script:
  - echo "Travis Run Project 3"

script:
  - docker build -t udagram-frontend ./udagram-frontend
  - docker tag udagram-frontend prinart/udagram-frontend
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker tag udagram-api-feed prinart/udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker tag udagram-api-user prinart/udagram-api-user
  - docker build -t reverseproxy ./udagram-reverseproxy
  - docker tag reverseproxy prinart/reverseproxy

after_script:
  - docker images
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push prinart/udagram-api-feed
  - docker push prinart/udagram-api-user
  - docker push prinart/udagram-frontend
  - docker push prinart/reverseproxy
